package com.practice;

// Generated by Selenium IDE
import org.apache.commons.io.FileUtils;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.io.File;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;



public class BcKieServerTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.gecko.driver", "driver/geckodriver");
        System.setProperty(FirefoxDriver.SystemProperty.BROWSER_LOGFILE,"firef_bckie.log");

        FirefoxOptions options = new FirefoxOptions();
        options.setLogLevel(FirefoxDriverLogLevel.TRACE);

        driver = new FirefoxDriver(options);

        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        driver.manage().timeouts().implicitlyWait(55, TimeUnit.SECONDS);
    }
    @After
    public void tearDown() {
        try {
            File scrFile = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
            FileUtils.copyFile(scrFile, new File("./image_bckie.png"));
        }
        catch(Exception e) {
            e.printStackTrace();
        }
        driver.quit();
    }
    @Test
    public void bcKieServer() {
        // Step # | name | target | value
        // 1 | open | /business-central/kie-wb.jsp |
        driver.get("http://localhost:8080/business-central/kie-wb.jsp");
        // 2 | setWindowSize | 1632x888 |
        driver.manage().window().setSize(new Dimension(1632, 888));
        // 3 | type | name=j_username | krisv
        driver.findElement(By.name("j_username")).sendKeys("krisv");
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 4 | type | name=j_password | krisv
        driver.findElement(By.name("j_password")).sendKeys("krisv");
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 5 | click | css=.button |
        driver.findElement(By.cssSelector(".button")).click();
        // 6 | runScript | window.scrollTo(0,0) |
        js.executeScript("window.scrollTo(0,0)");
        // 7 | click | linkText=projects |
        driver.findElement(By.linkText("projects")).click();
        // 8 | runScript | window.scrollTo(0,0) | MySpace charge
        js.executeScript("window.scrollTo(0,0)");
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 9 | click | css=.card-pf-body | load of MySpace
        driver.findElement(By.cssSelector(".card-pf-body")).click();
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 10 | waitForText | css=.blank-slate-pf-secondary-action > .btn:nth-child(1) | 30000
        driver.findElement(By.cssSelector(".blank-slate-pf-secondary-action > .btn:nth-child(1)")).click();
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 11 | click | css=.col-xs-12:nth-child(6) .card-pf-body |
        driver.findElement(By.cssSelector(".col-xs-12:nth-child(3) .card-pf-body")).click();
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 12 | click | css=.btn-primary |
        driver.findElement(By.cssSelector(".btn-primary")).click();
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 13 | runScript | window.scrollTo(0,0) |
        js.executeScript("window.scrollTo(0,0)");
        try {
            Thread.sleep(30000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 14 | click | id=build |
        driver.findElement(By.id("build")).click();
        try {
            Thread.sleep(30000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 15 | click | id=deploy |
        driver.findElement(By.id("deploy")).click();
        try {
            Thread.sleep(30000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 16 | click | css=#mega-menu-dropdown > .caret |
        driver.findElement(By.cssSelector("#mega-menu-dropdown > .caret")).click();
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 17 | click | linkText=Execution Servers |
        driver.findElement(By.linkText("Execution Servers")).click();
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 18 | runScript | window.scrollTo(0,0) |
        js.executeScript("window.scrollTo(0,0)");
        try {
            Thread.sleep(30000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 19 | click | css=.close |
        driver.findElement(By.cssSelector(".close")).click();
        // 20 | waitForElementPresent | css=.pficon-ok |
        {
            WebDriverWait wait = new WebDriverWait(driver, 40);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".pficon-ok")));
        }
        // 21 | click | css=#add-new-container > span |
        driver.findElement(By.cssSelector("#add-new-container > span")).click();
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 22 | runScript | window.scrollTo(0,0) |
        js.executeScript("window.scrollTo(0,0)");
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 23 | click | css=.btn-xs |
        driver.findElement(By.cssSelector(".btn-xs")).click();
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 24 | click | id=do-not-show-again |
        driver.findElement(By.id("do-not-show-again")).click();
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 25 | click | css=.modal-footer .btn-primary:nth-child(1) |
        driver.findElement(By.cssSelector(".modal-footer .btn-primary:nth-child(1)")).click();
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 26 | click | css=fieldset > .form-group:nth-child(2) > .form-control |
        driver.findElement(By.cssSelector("fieldset > .form-group:nth-child(2) > .form-control")).click();
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 27 | type | css=fieldset > .form-group:nth-child(2) > .form-control | podman-compose
        driver.findElement(By.cssSelector("fieldset > .form-group:nth-child(2) > .form-control")).sendKeys("bc-kie-server");
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 28 | click | css=.btn:nth-child(4) |
        driver.findElement(By.cssSelector(".btn:nth-child(4)")).click();
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 29 | click | id=container-config-start |
        driver.findElement(By.id("container-config-start")).click();
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 30 | waitForElementPresent | css=.pficon-ok |
        {
            WebDriverWait wait = new WebDriverWait(driver, 20);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".pficon-ok")));
        }
        // 31 | click | linkText=sample-server@kie-server:8080 |
        driver.findElement(By.cssSelector(".fa-server")).click();
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 32 | assertText | linkText=mortgages | mortgages
        assertThat(driver.findElement(By.linkText("mortgages")).getText(), is("mortgages"));
        // 33 | assertText | linkText=podman-compose | podman-compose
        assertThat(driver.findElement(By.linkText("bc-kie-server")).getText(), is("bc-kie-server"));
        // 34 | click | linkText=krisv |
        driver.findElement(By.linkText("krisv")).click();
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 35 | click | linkText=Log Out |
        driver.findElement(By.linkText("Log Out")).click();
    }
}