package com.practice;

// Generated by Selenium IDE
import org.apache.commons.io.FileUtils;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.io.File;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;


public class JbpmServerTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.gecko.driver", "driver/geckodriver");
        System.setProperty(FirefoxDriver.SystemProperty.BROWSER_LOGFILE,"firef_jbpm.log");

        FirefoxOptions options = new FirefoxOptions();
        options.setLogLevel(FirefoxDriverLogLevel.TRACE);

        driver = new FirefoxDriver(options);

        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        driver.manage().timeouts().implicitlyWait(40, TimeUnit.SECONDS);
    }
    @After
    public void tearDown() {
        try {
            File scrFile = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
            FileUtils.copyFile(scrFile, new File("./image_jbpm.png"));
        }
        catch(Exception e) {
            e.printStackTrace();
        }
        driver.quit();
    }
    @Test
    public void jbpmServer_i() {
        // Step # | name | target | value
        // 1 | open | /business-central/kie-wb.jsp |
        driver.get("http://localhost:8080/business-central/kie-wb.jsp");
        // 2 | setWindowSize | 1632x888 |
        driver.manage().window().setSize(new Dimension(1632, 888));
        // 3 | click | name=j_username |
        driver.findElement(By.name("j_username")).click();
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 4 | type | name=j_username | krisv
        driver.findElement(By.name("j_username")).sendKeys("krisv");
        // 5 | click | css=fieldset |
        driver.findElement(By.cssSelector("fieldset")).click();
        // 6 | click | name=j_password |
        driver.findElement(By.name("j_password")).click();
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 7 | type | name=j_password | krisv
        driver.findElement(By.name("j_password")).sendKeys("krisv");
        // 8 | click | css=.button |
        driver.findElement(By.cssSelector(".button")).click();
        // 9 | runScript | window.scrollTo(0,0) |
        js.executeScript("window.scrollTo(0,0)");
        driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 10 | click | linkText=projects |
        driver.findElement(By.linkText("projects")).click();
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 11 | runScript | window.scrollTo(0,0) | MySpace charge
        js.executeScript("window.scrollTo(0,0)");
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 12 | click | css=.card-pf-body | load of MySpace
        driver.findElement(By.cssSelector(".card-pf-body")).click();
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 13 | waitForText | css=.blank-slate-pf-secondary-action > .btn:nth-child(1) | 30000
        driver.findElement(By.cssSelector(".blank-slate-pf-secondary-action > .btn:nth-child(1)")).click();
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 14 | click | css=.col-xs-12:nth-child(6) .card-pf-body |
        driver.findElement(By.cssSelector(".col-xs-12:nth-child(3) .card-pf-body")).click();
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 15 | click | css=.btn-primary |
        driver.findElement(By.cssSelector(".btn-primary")).click();
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 16 | runScript | window.scrollTo(0,0) |
        js.executeScript("window.scrollTo(0,0)");
        try {
            Thread.sleep(10000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 17 | click | id=build |
        driver.findElement(By.id("build")).click();
        try {
            Thread.sleep(15000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 18 | click | linkText=krisv |
        driver.findElement(By.linkText("krisv")).click();
        // 19 | click | linkText=Log Out |
        driver.findElement(By.linkText("Log Out")).click();
    }
    @Test
    public void jbpmServer_ii() {
        // Step # | name | target | value
        // 1 | open | /kie-server/docs|
        driver.get("http://localhost:8080/kie-server/docs");
        // 2 | setWindowSize | 1632x911 |
        driver.manage().window().setSize(new Dimension(1632, 911));
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 3 | assertTitle | Execution Server Documentation |
        assertThat(driver.getTitle(), is("Execution Server Documentation"));
    }
    @Test
    public void jbpmServer_iii() {
        // Step # | name | target | value
        // 1 | open | http://localhost:8080/jbpm-casemgmt/jbpm-cm.html |
        driver.get("http://localhost:8080/jbpm-casemgmt/jbpm-cm.html");
        // 2 | type | id=j_username | wbadmin
        driver.findElement(By.id("j_username")).sendKeys("wbadmin");
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 3 | type | id=j_password | wbadmin
        driver.findElement(By.id("j_password")).sendKeys("wbadmin");
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 4 | click | css=.btn |
        driver.findElement(By.cssSelector(".btn")).click();
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 5 | runScript | window.scrollTo(0,0) |
        js.executeScript("window.scrollTo(0,0)");
        driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 6 | click | linkText=wbadmin |
        driver.findElement(By.linkText("wbadmin")).click();
        // 7 | click | linkText=Log Out |
        driver.findElement(By.linkText("Log Out")).click();
        // 8 | assertText | css=.alert | Logout successful
        assertThat(driver.findElement(By.cssSelector(".alert")).getText(), is("Logout successful"));
    }
}