{
 "title": "jBPM Kie Server Jobs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Running Jobs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_server_job_running_total)"
    }
   ]
  },
  {
   "title": "Average Job Execution Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_server_job_duration_seconds_sum) / sum(kie_server_job_duration_seconds_count)"
    }
   ]
  },
  {
   "title": "Executed Jobs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_server_job_executed_total)"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_server_job_executed_total{failed=\"true\"})"
    }
   ]
  },
  {
   "title": "Scheduled Jobs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_server_job_scheduled_total)"
    }
   ]
  },
  {
   "title": "Cancelled Jobs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "kie_server_job_cancelled_total" }
   ]
  },
  {
   "title": "Total Job Execution Time Per Command",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(kie_server_job_duration_seconds_sum) by (command_name)",
     "legendFormat": "{{command_name}}"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(kie_server_job_duration_seconds_sum[1m])",
     "legendFormat": "{{command_name}}"
    }
   ]
  }
 ]
}